### ISSUE TITLE
StreamBlobResponse should not return a promise

### ISSUE THREAD

**Issue by slightlytyler** [react-native-community/fetch#11]
I'm working on integrating this polyfill to enable text streaming in my app and have encountered a problem that goes like this:
```js
fetch('...').then(response => {
    console.log(response.headers); // map object
    const clone = response.clone();
    console.log(clone.headers); // undefined, and headers isn't optional
    clone.then(cloneResponse => {
        console.log(cloneResponse.headers); // map object
    })
})
```

It seems like StreamBlobResponse constructor should not return a promise https://github.com/react-native-community/fetch/blob/master/src/StreamBlobResponse.js#L11-L22

I experimented with removing the returns and that does seem to fix it. The implementation treats the respective class properties as optional so everything continues to work. Was this an oversight or is there a deeper reason that it's implemented like this which breaks the Response object?

**Comment by acostalima** [comment]
> Was this an oversight or is there a deeper reason that it's implemented like this which breaks the Response object?

It's most likely an oversight. 😅 
I haven't touched this code in a while, but I think we should be able to simplify dramatically the implementation of `StreamBlobResponse` and `StreamArrayBufferResponse` as `Response` and `Body` pretty much take care of everything. In fact, I'd go as far as renaming these classes to `BlobResponse` and `ArrayBufferResponse` as change the implementation as follows:

### BlobResponse 

```js
constructor(blobData, options) {
   const blob = BlobManager.createFromOptions(blobData);
   this._response = new Response(blob, options);
}
```

### ArrayBufferResponse 

```js
constructor(base64, options) {
   const buffer = toByteArray(base64);
   this._response = new Response(buffer, options);
}
```

The `Response` methods can be delegated to `_response`. I'm not 100% sure whether this approach works, as it remains to be tested, but it should.

**Comment by slightlytyler** [comment]
yep I can, thanks for taking a look!

**Comment by acostalima** [comment]
Thanks! 💪
