### ISSUE TITLE
Support for Expo

### ISSUE THREAD

**Issue by codergautam** [react-native-community/fetch#18]
Is there support for Expo in this module?

**Comment by codergautam** [comment]
I was able to get it working by installing the Polyfills from here:
https://github.com/acostalima/react-native-polyfill-globals

**Comment by Haseebshah936** [comment]
@codergautam can you share a code snippet for its implementation :)

**Comment by codergautam** [comment]
See my answer on stackoverflow https://stackoverflow.com/questions/56207968/stream-api-with-fetch-in-a-react-native-app/77089139#77089139
