### ISSUE TITLE
Slow iterations

### ISSUE THREAD

**Issue by GemsGame** [react-native-community/fetch#19]
Hello, I have issue with fetch, it's working extremally slow ~10 seconds for fetch and stream creation :(

I use React Native + Android Studio (virtual device) 

UPD: on the real phone it is works fine

**Comment by guillerp8** [comment]
Hi there,
I fixed this issue including in my backend this headers:
res.setHeader('Content-Type', 'text/event-stream');
res.setHeader('Cache-Control', 'no-cache');
res.setHeader('Connection', 'keep-alive');
