### ISSUE TITLE
Looking for collaborators

### ISSUE THREAD

**Issue by pcowgill** [react-native-community/fetch#2]
@qalqi @cpojer @mislav @MattiasBuelens @ambarc @mythz If any of you are interested in contributing to this `react-native-community/fetch` effort, please let me know!

For context on why this fork exists, see [this PR](https://github.com/react-native-community/fetch/pull/1/files).

Also, if anyone reading this is interested, feel free to comment here. Thanks!

**Comment by qalqi** [comment]
I can contribute

**Comment by pcowgill** [comment]
> I can contribute

Hi @alloy, it looks like @qalqi is interested in contributing as well.

**Comment by alloy** [comment]
Done 👍

**Comment by qalqi** [comment]
How are we taking forward? TDD should be good?

**Comment by acostalima** [comment]
If you guys are still looking forward to contribute somehow, please refer to and follow up at https://github.com/react-native-community/fetch/issues/4.
