### ISSUE TITLE
Implement response.body as a stream

### ISSUE THREAD

**Issue by pcowgill** [react-native-community/fetch#3]
Moving this issue https://github.com/github/fetch/issues/746 here

**Comment by pcowgill** [comment]
Getting `ipfs-http-client` working in React Native is part of the reason for having a spec-compliant implementation of `fetch` in React Native. Let's have the discussion from the end of the convo in the `github/fetch` issue above about IPFS in this `js-ipfs` issue https://github.com/ipfs/js-ipfs/issues/2847

**Comment by acostalima** [comment]
Please refer to and follow up at https://github.com/react-native-community/fetch/issues/4.
